# Generated by Django 6.0.6 on 2026-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=255, null=True, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(verbose_name='Ano de publicação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=255, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
