# Generated by Django 6.0.6 on 2026-07-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_usuario_delete_livro_delete_tarefamodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
